###
# This script is being generated by generate-inventory.sh
###

choice=1
while [ $choice!=0 ]; do
  echo ""
  echo 1 de-fra1-control-plane-master
  echo 2 de-fra1-control-plane-worker-0
  echo 0. exit
  echo ""
  echo -n "Select: "
  read choice
  case $choice in
  1) echo "de-fra1-control-plane-master"; ssh -o StrictHostKeyChecking=no clearlinux@10.4.6.202;;
  2) echo "de-fra1-control-plane-worker-0"; ssh -o StrictHostKeyChecking=no clearlinux@10.4.1.191;;
    *) echo ""; exit 0 ;;
  esac
done
